version: "3.9"

services:
  app:
    build: .
    container_name: app
    restart: always
    depends_on:
      mariadb:
        condition: service_started
    environment:
      DB_HOST: ${DB_HOST} # ${DB_HOST}
      DB_USER: ${DB_USER} # ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD} # ${DB_PASSWORD}
      DB_NAME: ${DB_NAME} # ${DB_NAME}
    ports:
      - "8000:5000"
    volumes:
      - .:/app

  mariadb:
      image: mariadb:11.3
      container_name: mariadb
      restart: always
      environment:
        MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MARIADB_DATABASE: ${DB_NAME}
        MARIADB_USER: ${DB_USER}
        MARIADB_PASSWORD: ${DB_PASSWORD}
        MARIADB_CHARACTER_SET_SERVER: utf8mb4
        MARIADB_COLLATION_SERVER: utf8mb4_unicode_ci
      ports:
        - "3306:3306"
      volumes:
        - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
